"""Generate outputs/summary.md and outputs/charts/*.png."""
from __future__ import annotations

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.ticker import MaxNLocator  # noqa: E402

from .config import ROOT, SCENARIOS, load_inputs, resolve  # noqa: E402
from .scenarios import (per_share_acquirer, run_all, sensitivity,  # noqa: E402
                        tornado, weighted_per_share)
from .valuation import diluted_shares, market_implied, multiples_grid  # noqa: E402

OUT = ROOT / "outputs"
COLORS = {"bear": "#c2410c", "base": "#1d4ed8", "bull": "#15803d"}


def _m(x: float) -> str:
    return f"{'−' if x < -0.5 else ''}${abs(x):,.0f}M"


def _ps(x: float) -> str:
    return f"{'−' if x < -0.005 else ''}${abs(x):,.2f}"


def _table(header: list[str], rows: list[list]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def charts(results: dict, tornado_rows: list[dict]) -> None:
    (OUT / "charts").mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(8, 4.5))
    for s, r in results.items():
        ax.plot([p["year"] for p in r["patients"]], [p["treated_end"] for p in r["patients"]],
                label=s, color=COLORS[s], linewidth=2)
    ax.set(title="US patients on therapy (year-end)", xlabel="", ylabel="patients")
    ax.grid(alpha=0.3)
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax.legend()
    fig.tight_layout()
    fig.savefig(OUT / "charts" / "patients.png", dpi=150)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 4.5))
    for s, r in results.items():
        years = [row["year"] for row in r["revenue"]]
        ax.plot(years, [row["ww_sales"] for row in r["revenue"]], label=f"{s} WW", color=COLORS[s], linewidth=2)
        ax.plot(years, [row["us_sales"] for row in r["revenue"]], color=COLORS[s], linewidth=1, linestyle="--")
    ax.set(title="Net sales, $M (solid = worldwide, dashed = US)", ylabel="$M")
    ax.grid(alpha=0.3)
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax.legend()
    fig.tight_layout()
    fig.savefig(OUT / "charts" / "revenue.png", dpi=150)
    plt.close(fig)

    top = tornado_rows[:12][::-1]
    base = results["base"]["valuation"]["per_share_acquirer"]
    fig, ax = plt.subplots(figsize=(8, 5.5))
    for i, row in enumerate(top):
        ax.barh(i, row["bear_value"] - base, left=base, color=COLORS["bear"])
        ax.barh(i, row["bull_value"] - base, left=base, color=COLORS["bull"])
    ax.axvline(base, color="black", linewidth=1)
    ax.set_yticks(range(len(top)), [row["driver"].split(".")[-1] for row in top], fontsize=8)
    ax.set(title=f"Tornado: acquirer-view rNPV/share (base {_ps(base)})", xlabel="$/share")
    fig.tight_layout()
    fig.savefig(OUT / "charts" / "tornado.png", dpi=150)
    plt.close(fig)


def main() -> None:
    inputs = load_inputs()
    results = run_all(inputs)
    base_inputs = {k: resolve(v, "base") for k, v in inputs.items()}
    company, deal, tl = base_inputs["company"], base_inputs["deal_terms"], base_inputs["timeline"]
    weights = tl["scenario_weights"]
    tornado_rows = tornado(inputs, metric=per_share_acquirer)
    charts(results, tornado_rows)

    price = company["price"]
    s = company["shares"]
    md = [f"# SPRB model output\n\nValuation date {tl['valuation_date']} · price {_ps(price)} "
          f"({company['price_date']}) · generated by `python run.py` — do not edit by hand.\n",
          "> Research artifact, not investment advice. Inputs tagged [assumption] in `inputs/*.yaml` drive everything.\n"]

    fd = diluted_shares(company, price)
    md += ["## Cap table\n", _table(["Item", "Shares"], [
        ["Basic (10-Q cover, 8/10/26)", f"{s['basic']:,}"],
        ["RSUs + options + ESPP (6/30/26)", f"{s['rsus'] + s['options'] + s['espp']:,}"],
        [f"Warrants/convert via TSM at {_ps(price)}", f"{fd - s['basic'] - s['rsus'] - s['options'] - s['espp']:,.0f}"],
        ["**Fully diluted**", f"**{fd:,.0f}**"],
        ["Fully diluted on change of control", f"{diluted_shares(company, price, change_of_control=True):,.0f}"],
    ]), ""]

    mi = market_implied(company, deal, tl)
    md += ["## What the market is pricing (base PoS / PRV)\n", _table(["", "Value"], [
        ["Market cap (FD)", _m(mi["market_cap"])],
        ["Cash (rolled to valuation date) − debt at face", f"{_m(mi['cash'])} − {_m(mi['debt'])} = {_m(mi['net_cash'])}"],
        ["Enterprise value", _m(mi["ev"])],
        ["Risked after-tax PRV", _m(mi["risked_after_tax_prv"])],
        ["**Implied value of TA-ERT**", f"**{_m(mi['implied_drug_value'])}**"],
        *[[f"Implied WW peak sales at {m}x", _m(v)] for m, v in mi["implied_peak_sales"].items()],
    ]), ""]

    rows = []
    for sc in SCENARIOS:
        r, v = results[sc], results[sc]["valuation"]
        rows.append([sc, _m(r["peak_ww_sales"]), r["peak_year"], f"{r['peak_us_treated']:.0f}", f"{v['pos']:.0%}",
                     f"{v['discount_rate']:.0%}", _ps(v["per_share_success"]), _ps(v["per_share_acquirer_success"]),
                     _ps(v["per_share_failure"]), f"**{_ps(v['per_share'])}**", f"**{_ps(v['per_share_acquirer'])}**",
                     f"{_m(v['min_net_cash_success'])} ({v['min_net_cash_year']})"])
    md += ["## rNPV by scenario\n",
           "Per share after the pre-approval raise, on FD shares. *Standalone* = Spruce commercializes alone; "
           "*acquirer* = a strategic owner strips G&A and part of SG&A from approval. Each branch is floored at $0 "
           "(limited liability) before probability-weighting.\n",
           _table(["Scenario", "Peak WW sales", "Peak yr", "Peak US pts", "PoS", "WACC", "Success: standalone",
                   "Success: acquirer", "Failure", "rNPV standalone", "rNPV acquirer",
                   "Low point of net cash, standalone success"], rows),
           f"\nProbability-weighted ({'/'.join(f'{w:.0%}' for w in weights)}): standalone "
           f"**{_ps(weighted_per_share(results, weights))}**, acquirer "
           f"**{_ps(weighted_per_share(results, weights, 'per_share_acquirer'))}** vs price {_ps(price)}.\n",
           "A negative net-cash low point means the modeled raise is not enough — more dilution than modeled.\n",
           "![patients](charts/patients.png)\n", "![revenue](charts/revenue.png)\n"]

    grid = multiples_grid(company, deal, tl)
    md += ["## EV / peak-sales grid ($/share)\n",
           f"(peak × multiple × (1 − {tl['multiples_grid']['royalty_haircut']:.0%} royalty haircut) × PoS {grid['pos']:.0%} "
           f"+ risked after-tax PRV + net cash + raise) / {grid['shares']:,.0f} shares. Multiples are for an approved asset, "
           "so PoS is applied once.\n",
           _table(["WW peak"] + [f"{m}x" for m in grid["multiples"]],
                  [[_m(peak)] + [_ps(v) for v in cols.values()] for peak, cols in grid["table"].items()]), ""]

    md += ["## Tornado (acquirer-view rNPV/share; each input to bear/bull, rest at base)\n",
           _table(["Driver", "Bear → Base → Bull input", "At bear", "At bull", "Swing"],
                  [[row["driver"], f"{row['bear_input']} → {row['base_input']} → {row['bull_input']}",
                    _ps(row["bear_value"]), _ps(row["bull_value"]), _ps(row["swing"])] for row in tornado_rows]),
           "\n![tornado](charts/tornado.png)\n"]

    sens = tl["sensitivity"]
    table = sensitivity(inputs, ("epidemiology", "incidence_per_100k"), sens["incidence_per_100k"],
                        ("pricing", "us_wac_k"), sens["us_wac_k"], metric=per_share_acquirer)
    md += ["## Sensitivity: acquirer rNPV/share vs incidence × US WAC (base otherwise)\n",
           _table(["Incidence /100k (US prevalent)"] + [f"WAC ${w}k" for w in sens["us_wac_k"]],
                  [[f"{inc} (~{inc * 3.6e6 / 1e5 * resolve(inputs['epidemiology']['untreated_life_years'], 'base'):.0f})"]
                   + [_ps(v) for v in cols.values()] for inc, cols in table.items()]), ""]

    base_pnl = results["base"]["pnl"]
    keys = [("ww_sales", "WW net sales"), ("total_revenue", "Spruce revenue"), ("cogs", "COGS"),
            ("biomarin_royalty", "BioMarin royalty"), ("regulatory_milestones", "Reg. milestones"),
            ("sales_milestones", "Sales milestones"), ("rd", "R&D"), ("ga", "G&A"), ("sga_us", "US SG&A"),
            ("sga_exus", "Ex-US SG&A"), ("prv_proceeds", "PRV"), ("tax", "Tax"),
            ("fcf_success", "FCF standalone"), ("fcf_acquirer", "FCF acquirer"), ("fcf_failure", "FCF if not approved")]
    shown = [r for r in base_pnl if r["year"] <= 2036 or r["year"] % 3 == 0]
    md += ["## Base case annual detail ($M; 2026 = rest of year)\n",
           _table(["Line"] + [str(r["year"]) for r in shown],
                  [[label] + [f"{r[k]:,.1f}" for r in shown] for k, label in keys]), ""]

    (OUT / "summary.md").write_text("\n".join(md))
    print(f"wrote {OUT / 'summary.md'}")
